version: "3"
services:
  etls:
    working_dir: /srv
    volumes:
      - ./:/srv
    build:
      context: ./
    ports:
      - "0.0.0.0:5000:5000"
    environment:
      DB_URL: postgresql://user:pass@db:5432/public_apis_api
    command: bash -c "pip install -r requirements.txt && flask run --debug --host=0.0.0.0 -p 5000"
  db:
    image: ankane/pgvector
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: public_apis_api
